spring:
  application:
    name: review-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/review_db
#    username: postgres
#    password: 3ea14367A4
#    driver-class-name: org.postgresql.Driver

  datasource:
      url: jdbc:mysql://localhost:3306/nwtdbAjla
      username: root
      password: root


  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    #hibernate.ddl-auto=update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  cloud:
    config:
      enabled: false

server:
  port: 0

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

jwt:
  secret: "100aa60b3972fe7bc2aa2f7358d7b6d052e86e9bafa85c9fa335e203b7281846"
  ExpirationTime: 36000000

logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG

gateway:
  ip: 192.168.1.7
